// Animation and timing constants used across the application

export const ANIMATION_TIMINGS = {
  FAST: 150,
  NORMAL: 300,
  SLOW: 500,
  FOCUS_DELAY: 100,
  MODAL_TRANSITION: 300,
  SEARCH_DEBOUNCE: 250,
  CAMERA_ANIMATION: 2000,
  ARC_ANIMATION: 1000
};

export const SIZES = {
  MIN_QUERY_LENGTH: 2,
  MAX_SEARCH_RESULTS: 50,
  DEFAULT_SEARCH_LIMIT: 20,
  POINT_RADIUS_HQ: 0.08,
  POINT_RADIUS_OFFICE: 0.06,
  LABEL_SIZE_MULTIPLIER: 1.4
};

export const GLOBE_CONFIG = {
  RADIUS: 100,
  ATMOSPHERE_ALTITUDE: 0.25,
  HEX_POLYGON_RESOLUTION: 3,
  HEX_POLYGON_MARGIN: 0.7,
  ARC_ALTITUDE: 0.3,
  POINT_ALTITUDE: 0.07,
  LABEL_ALTITUDE: 0.01,
  ROTATION_SPEED: 0.001,
  CAMERA_DISTANCE_MULTIPLIER: 2.5
};

export const ZYETA_COLORS = {
  PRIMARY_BLUE: '#00d4ff',
  GOLD: '#ffd700',
  DEFAULT_COUNTRY: 'rgba(255, 255, 255, 0.5)',
  ATMOSPHERE: '#3a228a',
  GLOBE_SURFACE: '#061621',
  GLOBE_EMISSIVE: '#062038',
  ARC_ACTIVE: '#00d4ff',
  ARC_INACTIVE: '#ff6b6b'
};

export const KEYBOARD_SHORTCUTS = {
  ESCAPE: 'escape',
  SAVE: 'ctrl+s',
  SEARCH: 'ctrl+f',
  FOCUS_SEARCH: '/',
  CLOSE_MODAL: 'escape'
};